version: "3"
services:
  db:
    container_name: quiz-server-side
    restart: always
    image: postgres # use latest official postgres version
    environment:
      POSTGRES_USER: root # configure postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: service
    volumes:
      - lab-server-side:/var/lib/postgresql/data/ # persist data even if container shuts down
    # env_file:
    #   - ./.env
    expose:
      - 5434
    ports:
      - 5434:5434
    command: -p 5434
    networks:
      - application-network

volumes:
  lab-server-side: # named volumes can be managed easier using docker-compose
    driver: local

networks:
  application-network:
    driver: bridge
